#!/usr/bin/env node

// @pedrofariasx/toolstream — Postinstall Script
// Creates AI-friendly context files for AI tool integration

import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs"
import { resolve, join, dirname } from "node:path"
import { fileURLToPath } from "node:url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

const PACKAGE_ROOT = resolve(__dirname, "..")
const PKG_NAME = "@pedrofariasx/toolstream"

// Determine the user's project root from INIT_CWD (set by npm/pnpm/yarn)
const userProjectDir = process.env.INIT_CWD || process.cwd()

// Write AI context inside node_modules for tooling that scans node_modules
const aiContextDir = resolve(PACKAGE_ROOT, ".ai-context")
const aiContextPath = join(aiContextDir, "integration.md")

if (!existsSync(aiContextDir)) {
	mkdirSync(aiContextDir, { recursive: true })
}

const packageJson = JSON.parse(readFileSync(join(PACKAGE_ROOT, "package.json"), "utf-8"))

const aiContext = `# ${PKG_NAME} v${packageJson.version}

## Quick Integration

\`\`\`typescript
import { ToolStream } from "${PKG_NAME}"

const parser = new ToolStream({ provider: "openai" })

parser.on("tool-call:complete", (toolCall) => {
  console.log(\`Tool: \${toolCall.name}\`, toolCall.arguments)
})

// Feed chunks from your LLM stream
for await (const chunk of stream) {
  parser.push(chunk)
}

const results = parser.finalize()
\`\`\`

## Available Imports

| Import Path | Exports |
|-------------|---------|
| \`${PKG_NAME}\` | ToolStream, ToolStreamEmitter, ToolCallStateMachine, Tokenizer, JsonStreamParser, JsonRepairer, Normalizer, RecoveryEngine, ConfidenceScorer, adapterRegistry, types |
| \`${PKG_NAME}/adapters\` | OpenAIAdapter, AnthropicAdapter, GeminiAdapter, DeepSeekAdapter, QwenAdapter, XmlAdapter, MarkdownAdapter, FunctionTagAdapter, BaseAdapter |
| \`${PKG_NAME}/ai\` | getAIManifest(), getIntegrationGuide() |

## Providers

Create a parser with \`new ToolStream({ provider: 'openai' })\` or enable auto-detection with \`{ autoDetectProvider: true }\`.

Supported: \`openai\`, \`anthropic\`, \`gemini\`, \`deepseek\`, \`qwen\`, \`xml\`, \`markdown\`.

## Events

Subscribe to events: \`parser.on('tool-call:complete', handler)\`

Events: \`text\`, \`tool-call:start\`, \`tool-call:id\`, \`tool-call:name\`, \`tool-call:arguments:delta\`, \`tool-call:arguments:key\`, \`tool-call:arguments:value\`, \`tool-call:arguments:partial\`, \`tool-call:early-execute\`, \`tool-call:complete\`, \`tool-call:error\`.

## AI Manifest

Structured metadata available at: \`node_modules/${PKG_NAME}/ai/manifest.json\`

## Runtime Support

Node.js >= 18, Bun, Deno, Browser, Cloudflare Workers.
`

writeFileSync(aiContextPath, aiContext, "utf-8")

// Also try to create a symlink / reference in the user's project .claude directory
const claudeDir = join(userProjectDir, ".claude", "sources")
const claudeFilePath = join(claudeDir, "toolstream.md")

try {
	if (!existsSync(claudeDir)) {
		mkdirSync(claudeDir, { recursive: true })
	}

	const guideContent = readFileSync(join(PACKAGE_ROOT, "ai", "CLAUDE.md"), "utf-8")
	const userGuide = `<!-- Auto-generated by ${PKG_NAME} postinstall -->\n\n${guideContent}`
	writeFileSync(claudeFilePath, userGuide, "utf-8")
} catch {
	// Fail silently — user may not have a .claude directory or permissions
}

console.log(`\n  ✅ ${PKG_NAME} v${packageJson.version} installed`)
console.log(`  📖 AI manifest: node_modules/${PKG_NAME}/ai/manifest.json`)
console.log(`  🤖 AI-ready: importing ToolStream from "${PKG_NAME}"\n`)
